wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    session_history: code/_session_history.ipynb
    start_time: 1639494260
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 2
      - 16
      4: 3.8.10
      5: 0.12.7
      8:
      - 1
      - 5
dataset:
  desc: null
  value: celebA
nota:
  desc: null
  value: DGX
type:
  desc: null
  value: PG-GAN
